### ISSUE TITLE
Code for reproducing Fig. 1

### ISSUE THREAD

**Issue by AvivNavon** [tfjgeorge/ntk_alignment#1]
Thanks for this excellent paper and repo. 
Could you please share the code for reproducing Fig. 1 from the paper?
Thanks

**Comment by tfjgeorge** [comment]
Hi, I just pushed a colab with everything you need here: https://github.com/tfjgeorge/ntk_alignment/blob/master/NTK_alignment_viz_on_toy_datasets.ipynb

**Comment by AvivNavon** [comment]
Thanks!
